### ISSUE TITLE
Cov(X_i, u_i) is always going to be 0 by construction

### ISSUE THREAD

**Issue by HariharanJayashankar** [arnavs/ECON-326-Project#2]
A super interesting repo. A small point here which I didn't know how else to bring up. In the notebook you say that Cov(X_i, u_i) is 0. But this will always be the case with a regression by construction, no? 
Ref: https://stats.stackexchange.com/a/263327/115120

**Comment by arnavs** [comment]
You're right, it's guaranteed to be uncorrelated. This is the difference between [errors and residuals](https://en.wikipedia.org/wiki/Errors_and_residuals). Will remove that note.
